"""
Module 2: UPI Lookup Engine.

For each parsed trade, locate the matching ANNA-DSB product-definition template
and validate the trade's attribute values against the codesets the template
references. Two output statuses are used:

  FOUND                   - a template was located (exact or heuristic match);
                            validation errors / warnings, if any, are reported
                            in their respective lists. The classification_note
                            field carries an explanation when the match was
                            heuristic rather than exact.
  NO_PRODUCT_DEFINITION   - the trade was flagged NOVEL_INSTRUMENT_NO_TAXONOMY
                            in Module 1 (T026-T028 prediction contracts);
                            template lookup is bypassed.

UPI codes are returned as `null`: ANNA-DSB templates are JSON Schemas, not
records, and the UPI string for a specific product instance is generated by
DSB's live API at registration time. The cloned repo cannot supply it.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Allow `from module1_parser import ...` whether run via "python src/module2_upi_lookup.py"
# or imported as a module.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from module1_parser import ParsedTrade, parse_trades_file  # noqa: E402


# Trade-side asset-class label -> on-disk folder name.
ASSET_CLASS_FOLDERS: dict[str, str] = {
    "Rates": "Rates",
    "Credit": "Credit",
    "Equity": "Equity",
    "Commodities": "Commodities",
    "FX": "Foreign_Exchange",
}

VALID_TERM_UNITS = frozenset({"DAYS", "WEEK", "MNTH", "YEAR"})
VALID_DELIVERY_TYPES = frozenset({"CASH", "PHYS", "OPTL"})
VALID_DEBT_SENIORITIES = frozenset({"SNDB", "MZZD", "SBOD", "JUND"})

CODESET_FILES = {
    "currency": "ISOCurrencyCode",
    "rates": "FpmlRatesReferenceRate",
    "inflation": "FpmlRatesInflationRate",
}

NOVEL_NOTE = (
    "Instrument type {it!r} under asset class {ac!r} has no product "
    "definition in the ANNA-DSB UPI library. This reflects the current "
    "regulatory classification of prediction and event contracts as outside "
    "the OTC derivatives taxonomy in most jurisdictions. Refer to Module 4 "
    "for classification analysis."
)


# --- codeset / template loaders -----------------------------------------

def _load_codeset(name: str, repo_root: Path) -> set[str]:
    path = repo_root / "PROD" / "OTC-Products" / "codesets" / f"{name}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    return set(data.get("enum", []))


def _load_all_codesets(repo_root: Path) -> dict[str, set[str]]:
    return {key: _load_codeset(name, repo_root) for key, name in CODESET_FILES.items()}


# --- tokenisation -------------------------------------------------------

# Splits a CamelCase (or all-caps) chunk into tokens.
# Order matters: try TitleCase, then ALL-CAPS-followed-by-Title, then plain runs.
_CAMEL_RE = re.compile(r"[A-Z][a-z]+|[A-Z]+(?=[A-Z][a-z])|[A-Z]+|[a-z]+|\d+")


def _tokenize(s: str | None) -> set[str]:
    """Lowercase token set from a snake_case + CamelCase string."""
    if not s:
        return set()
    out: list[str] = []
    for chunk in s.split("_"):
        out.extend(_CAMEL_RE.findall(chunk))
    return {t.lower() for t in out if t}


def _trade_subject_hint(raw_trade: dict | None) -> set[str]:
    """
    A small set of disambiguating tokens derived from the trade payload.
    Helps the heuristic pick Single_Name vs Single_Index vs Basket templates
    when the use_case alone is too vague (e.g. Equity Variance swaps).
    """
    if not raw_trade:
        return set()
    if isinstance(raw_trade.get("underlying_isin"), str):
        return {"single", "name"}
    if raw_trade.get("underlying_index") or raw_trade.get("index_name"):
        return {"single", "index"}
    if raw_trade.get("underlying_basket"):
        return {"basket"}
    return set()


# --- template enumeration & matching ------------------------------------

@dataclass(frozen=True)
class TemplateCandidate:
    path: Path
    instrument_type: str  # InstrumentType segment from filename
    use_case: str         # UseCase segment from filename
    version: tuple[int, int]  # (major, modification)


_TEMPLATE_NAME_RE_FMT = (
    r"^{folder}\.(?P<it>[^.]+)\.(?P<uc>.+)\.UPI\.V(?P<v>\d+)(?:M(?P<m>\d+))?$"
)


def _enumerate_candidates(folder_name: str, repo_root: Path) -> list[TemplateCandidate]:
    folder = repo_root / "PROD" / "OTC-Products" / "UPI" / folder_name
    if not folder.exists():
        return []
    pattern = re.compile(_TEMPLATE_NAME_RE_FMT.format(folder=re.escape(folder_name)))
    out: list[TemplateCandidate] = []
    for path in folder.glob(f"{folder_name}.*.UPI.V*.json"):
        m = pattern.match(path.stem)
        if not m:
            continue
        out.append(
            TemplateCandidate(
                path=path,
                instrument_type=m.group("it"),
                use_case=m.group("uc"),
                version=(int(m.group("v")), int(m.group("m") or 0)),
            )
        )
    return out


def find_product_template(
    asset_class: str | None,
    instrument_type: str | None,
    use_case: str | None,
    repo_root: Path,
    raw_trade: dict | None = None,
) -> tuple[Path | None, str]:
    """
    Locate the best-matching template file.

    Returns (path, kind) where kind is one of:
        "exact"     - filename matches AssetClass.InstrumentType.UseCase exactly
        "heuristic" - matched by tokenised similarity (review recommended)
        "none"     - no template found at all
    """
    if not asset_class or not instrument_type or not use_case:
        return None, "none"

    folder_name = ASSET_CLASS_FOLDERS.get(asset_class, asset_class)
    candidates = _enumerate_candidates(folder_name, repo_root)
    if not candidates:
        return None, "none"

    # 1) exact match on the (InstrumentType, UseCase) segments — pick latest version.
    exact = [
        c for c in candidates
        if c.instrument_type == instrument_type and c.use_case == use_case
    ]
    if exact:
        return max(exact, key=lambda c: c.version).path, "exact"

    # 2) heuristic: token-overlap score.
    target = _tokenize(instrument_type) | _tokenize(use_case) | _trade_subject_hint(raw_trade)
    if not target:
        return None, "none"

    best: TemplateCandidate | None = None
    best_score = -1
    best_version: tuple[int, int] = (-1, -1)
    for c in candidates:
        tpl_tokens = _tokenize(c.instrument_type) | _tokenize(c.use_case)
        common = len(target & tpl_tokens)
        if common == 0:
            continue
        score = common * 10 - len(tpl_tokens - target)
        # Prefer higher score, break ties on higher version (more recent definition).
        if (score, c.version) > (best_score, best_version):
            best_score, best_version, best = score, c.version, c

    if best is None:
        return None, "none"
    return best.path, "heuristic"


# --- validation primitives ----------------------------------------------

def _push_error(errors: list[str], msg: str) -> None:
    errors.append(msg)


def _push_warning(warnings: list[str], msg: str) -> None:
    warnings.append(msg)


def _validate_currency(trade: dict, codesets: dict[str, set[str]],
                       errors: list[str], warnings: list[str]) -> None:
    val = trade.get("notional_currency")
    if val is None:
        return
    if not isinstance(val, str):
        _push_error(errors, f"notional_currency: expected string, got {type(val).__name__}")
        return
    if val not in codesets["currency"]:
        _push_error(errors, f"notional_currency: unknown ISO 4217 code {val!r}")


def _validate_one_reference_rate(field_name: str, val: Any,
                                 codesets: dict[str, set[str]],
                                 errors: list[str], warnings: list[str]) -> None:
    if val is None:
        return
    if not isinstance(val, str):
        _push_error(errors, f"{field_name}: expected string, got {type(val).__name__}")
        return
    if "LIBOR" in val:
        _push_warning(
            warnings,
            f"{field_name}: {val!r} is a LIBOR rate — deprecated since June 2023 cessation",
        )
        return
    if val in codesets["rates"] or val in codesets["inflation"]:
        return
    _push_error(
        errors,
        f"{field_name}: unknown reference rate {val!r} "
        f"(not in FpmlRatesReferenceRate or FpmlRatesInflationRate codesets)",
    )


def _validate_reference_rates(trade: dict, codesets: dict[str, set[str]],
                              errors: list[str], warnings: list[str]) -> None:
    for fname in ("reference_rate", "reference_rate_leg1", "reference_rate_leg2"):
        if fname in trade:
            _validate_one_reference_rate(fname, trade.get(fname), codesets, errors, warnings)


def _validate_term(trade: dict, errors: list[str], warnings: list[str]) -> None:
    pairs = [
        ("reference_rate_term_value", "reference_rate_term_unit"),
        ("reference_rate_term_leg1_value", "reference_rate_term_leg1_unit"),
        ("reference_rate_term_leg2_value", "reference_rate_term_leg2_unit"),
    ]
    for v_name, u_name in pairs:
        if v_name in trade:
            v = trade.get(v_name)
            if v is not None:
                if isinstance(v, bool) or not isinstance(v, int):
                    _push_error(errors, f"{v_name}: expected integer, got {type(v).__name__}")
                elif v == 0:
                    _push_error(errors, f"{v_name}: must not be zero")
                elif v < -999 or v > 999:
                    _push_error(errors, f"{v_name}: {v} outside allowed range [-999, 999]")
        if u_name in trade:
            u = trade.get(u_name)
            if u is not None:
                if not isinstance(u, str) or u not in VALID_TERM_UNITS:
                    _push_error(errors, f"{u_name}: {u!r} not in {sorted(VALID_TERM_UNITS)}")


def _validate_debt_seniority(trade: dict, errors: list[str], warnings: list[str]) -> None:
    if "debt_seniority" not in trade:
        return
    val = trade.get("debt_seniority")
    if val is None:
        return
    if not isinstance(val, str) or val not in VALID_DEBT_SENIORITIES:
        _push_error(errors, f"debt_seniority: {val!r} not in {sorted(VALID_DEBT_SENIORITIES)}")


def _validate_delivery_type(trade: dict, errors: list[str], warnings: list[str]) -> None:
    if "delivery_type" not in trade:
        return
    val = trade.get("delivery_type")
    if val is None:
        return
    if not isinstance(val, str) or val not in VALID_DELIVERY_TYPES:
        _push_error(errors, f"delivery_type: {val!r} not in {sorted(VALID_DELIVERY_TYPES)}")


def validate_attributes(
    trade: dict, template: dict, codesets: dict[str, set[str]] | None = None,
) -> tuple[list[str], list[str]]:
    """
    Validate the six attributes the brief enumerates: currency, reference rate
    (with LIBOR warning), term unit, term value range, debt seniority,
    delivery type. Multi-leg trades validate both legs.
    """
    if codesets is None:
        codesets = {"currency": set(), "rates": set(), "inflation": set()}
    errors: list[str] = []
    warnings: list[str] = []
    _validate_currency(trade, codesets, errors, warnings)
    _validate_reference_rates(trade, codesets, errors, warnings)
    _validate_term(trade, errors, warnings)
    _validate_debt_seniority(trade, errors, warnings)
    _validate_delivery_type(trade, errors, warnings)
    return errors, warnings


# --- top-level lookup ---------------------------------------------------

_VERSION_SUFFIX_RE = re.compile(r"\.UPI\.V\d+(?:M\d+)?$")


def lookup_upi(
    parsed_trade: ParsedTrade,
    raw_trade: dict,
    repo_root: Path,
    codesets: dict[str, set[str]],
) -> dict[str, Any]:
    """
    Returns the per-trade lookup record described in the assignment brief.
    Statuses: FOUND | NO_PRODUCT_DEFINITION.
    """
    record: dict[str, Any] = {
        "trade_id": parsed_trade.trade_id,
        "status": "FOUND",
        "matched_template": None,
        "upi_code": None,
        "classification_note": None,
        "validation_errors": [],
        "warnings": [],
    }

    if parsed_trade.classification_flag == "NOVEL_INSTRUMENT_NO_TAXONOMY":
        record["status"] = "NO_PRODUCT_DEFINITION"
        record["classification_note"] = NOVEL_NOTE.format(
            it=parsed_trade.instrument_type, ac=parsed_trade.asset_class,
        )
        return record

    template_path, kind = find_product_template(
        parsed_trade.asset_class,
        parsed_trade.instrument_type,
        parsed_trade.use_case,
        repo_root,
        raw_trade=raw_trade,
    )

    if template_path is None:
        record["classification_note"] = (
            f"No template located for asset_class={parsed_trade.asset_class!r}, "
            f"instrument_type={parsed_trade.instrument_type!r}, "
            f"use_case={parsed_trade.use_case!r} in the ANNA-DSB UPI library. "
            f"Asset class is in scope but this combination is not represented "
            f"in the published 143 templates."
        )
        return record

    template = json.loads(template_path.read_text(encoding="utf-8"))
    matched_stem = _VERSION_SUFFIX_RE.sub("", template_path.stem)
    record["matched_template"] = matched_stem

    errors, warnings = validate_attributes(raw_trade, template, codesets)
    record["validation_errors"] = errors
    record["warnings"] = warnings

    if kind == "heuristic":
        record["classification_note"] = (
            f"Heuristic template match: ({parsed_trade.asset_class}, "
            f"{parsed_trade.instrument_type}, {parsed_trade.use_case}) did not "
            f"match any template stem exactly; closest by token overlap is "
            f"{matched_stem!r}. Manual review recommended."
        )

    return record


# --- CLI ----------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Module 2: UPI lookup")
    ap.add_argument("--trades", default="data/trades.json")
    ap.add_argument("--library", default="data/product_definitions")
    ap.add_argument("--output", default="output/upi_lookup.json")
    args = ap.parse_args(argv)

    repo_root = Path(args.library)
    codesets = _load_all_codesets(repo_root)

    raw_trades = json.loads(Path(args.trades).read_text(encoding="utf-8"))
    raw_by_id = {t.get("trade_id"): t for t in raw_trades if isinstance(t, dict)}

    parsed = parse_trades_file(args.trades)

    out = [
        lookup_upi(p, raw_by_id.get(p.trade_id, {}), repo_root, codesets)
        for p in parsed
    ]

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(json.dumps(out, indent=2), encoding="utf-8")

    by_status: dict[str, int] = {}
    n_errors = n_warnings = n_heuristic = n_exact = 0
    for r in out:
        by_status[r["status"]] = by_status.get(r["status"], 0) + 1
        if r["validation_errors"]:
            n_errors += 1
        if r["warnings"]:
            n_warnings += 1
        if r["classification_note"] and "Heuristic" in r["classification_note"]:
            n_heuristic += 1
        elif r["status"] == "FOUND" and r["classification_note"] is None:
            n_exact += 1

    print(f"UPI lookup: {len(out)} trades -> {args.output}")
    print(f"  status:               {by_status}")
    print(f"  exact template match: {n_exact}")
    print(f"  heuristic match:      {n_heuristic}")
    print(f"  with errors:          {n_errors}")
    print(f"  with warnings:        {n_warnings}")
    for r in out:
        if r["validation_errors"] or r["warnings"]:
            print(
                f"  - {r['trade_id']}: status={r['status']} "
                f"errors={r['validation_errors']} warnings={r['warnings']}"
            )

    return 0


if __name__ == "__main__":
    sys.exit(main())
